"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 17:26:09.176541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('spotify_url', sa.String(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_songs'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('spotify_token', sa.String(), nullable=True),
    sa.Column('spotify_refresh_token', sa.String(), nullable=True),
    sa.Column('spotify_expires_at', sa.Integer(), nullable=True),
    sa.Column('garmin_username', sa.String(), nullable=True),
    sa.Column('garmin_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('fk_friend_requests_receiver_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_friend_requests_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friend_requests'))
    )
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], name=op.f('fk_friends_friend_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_friends_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'friend_id', name=op.f('pk_friends'))
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('avg_pace', sa.Float(), nullable=True),
    sa.Column('fit_file_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_runs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    op.create_table('user_song_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.String(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.Column('time_played', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_user_song_history_run_id_runs')),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_user_song_history_song_id_songs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_song_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_song_history'))
    )
    op.create_table('run_song_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('user_song_id', sa.Integer(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_song_analysis_run_id_runs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_run_song_analysis_user_id_users')),
    sa.ForeignKeyConstraint(['user_song_id'], ['user_song_history.id'], name=op.f('fk_run_song_analysis_user_song_id_user_song_history')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_song_analysis'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_song_analysis')
    op.drop_table('user_song_history')
    op.drop_table('runs')
    op.drop_table('friends')
    op.drop_table('friend_requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('songs')
    # ### end Alembic commands ###
