"""garmin session tokens

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-09 18:05:04.270886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garmin_tokens', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('garmin_sync_state', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('garmin_sync_message', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('garmin_last_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('garmin_last_synced_at')
        batch_op.drop_column('garmin_sync_message')
        batch_op.drop_column('garmin_sync_state')
        batch_op.drop_column('garmin_tokens')

    # ### end Alembic commands ###
