"""history import status

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-09 18:13:22.056570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history_import_state', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('history_import_message', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('history_imported_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('history_imported_at')
        batch_op.drop_column('history_import_message')
        batch_op.drop_column('history_import_state')

    # ### end Alembic commands ###
