"""song effects and skips

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-09 18:37:55.239939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_song_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pace_delta', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hr_delta', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('position', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('method_version', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_run_song_analysis_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_song_analysis_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_song_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skipped', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_song_history_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_song_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_song_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_song_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_song_history_run_id'))
        batch_op.drop_column('skipped')

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_user_id'))

    with op.batch_alter_table('run_song_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_song_analysis_user_id'))
        batch_op.drop_index(batch_op.f('ix_run_song_analysis_run_id'))
        batch_op.drop_column('method_version')
        batch_op.drop_column('position')
        batch_op.drop_column('seconds')
        batch_op.drop_column('hr_delta')
        batch_op.drop_column('pace_delta')

    # ### end Alembic commands ###
