"""consent

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-09 18:50:52.796915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0012'
down_revision = '0011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_consent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('policy_version', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('policy_version')
        batch_op.drop_column('data_consent_at')
        batch_op.drop_column('terms_accepted_at')

    # ### end Alembic commands ###
