"""Generate Runnify's favicon set from one geometric definition.

The mark is a results sheet: an ink square with two printed rows and, between
them, the best row struck through with highlighter. Shapes are axis-aligned
rectangles on a 32-unit grid, so every size is drawn with exact (area
coverage) anti-aliasing. Standard library only.

Run from the repository root:

    uv run python scripts/build_icons.py

Writes to runnify/static/img/: favicon.svg, favicon.ico (16, 32, 48 px),
apple-touch-icon.png (180 px), icon-192.png, icon-512.png and
runnify/static/site.webmanifest. Each PNG records this script as its source.
"""

import json
import struct
import zlib
from pathlib import Path

INK = (0x11, 0x11, 0x11)
PAPER = (0xFF, 0xFF, 0xFF)
HIGHLIGHT = (0xE8, 0xFF, 0x3A)

GRID = 32
# (x, y, width, height, colour) on the 32-unit grid, drawn in order over an ink square
SHAPES = (
    (6, 7, 20, 2, PAPER),  # printed row
    (5, 13, 22, 6, HIGHLIGHT),  # the best row, highlighted
    (6, 23, 14, 2, PAPER),  # printed row
)

OUT = Path(__file__).resolve().parent.parent / "runnify" / "static"
SOURCE_NOTE = "Generated by scripts/build_icons.py (Runnify results-sheet mark)"


def _coverage(px, py, x0, y0, x1, y1):
    """Fraction of the unit pixel at (px, py) covered by the rectangle [x0, x1) x [y0, y1)."""
    width = max(0.0, min(px + 1, x1) - max(px, x0))
    height = max(0.0, min(py + 1, y1) - max(py, y0))
    return width * height


def render(size):
    """Return ``size`` x ``size`` RGB rows for the mark."""
    scale = size / GRID
    pixels = [[list(INK) for _ in range(size)] for _ in range(size)]
    for x, y, w, h, colour in SHAPES:
        x0, y0, x1, y1 = x * scale, y * scale, (x + w) * scale, (y + h) * scale
        for py in range(int(y0), min(size, int(y1) + 1)):
            for px in range(int(x0), min(size, int(x1) + 1)):
                alpha = _coverage(px, py, x0, y0, x1, y1)
                if alpha:
                    pixel = pixels[py][px]
                    for c in range(3):
                        pixel[c] = round(pixel[c] * (1 - alpha) + colour[c] * alpha)
    return pixels


def _chunk(kind, data):
    body = kind + data
    return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)


def png(size):
    """Encode the mark as a PNG with a tEXt chunk naming its source."""
    raw = b"".join(b"\x00" + bytes(v for pixel in row for v in pixel) for row in render(size))
    return b"".join(
        [
            b"\x89PNG\r\n\x1a\n",
            _chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0)),
            _chunk(b"tEXt", b"Source\x00" + SOURCE_NOTE.encode("latin-1")),
            _chunk(b"IDAT", zlib.compress(raw, 9)),
            _chunk(b"IEND", b""),
        ]
    )


def ico(sizes):
    """Pack PNG images of ``sizes`` into a .ico file."""
    images = [png(size) for size in sizes]
    offset = 6 + 16 * len(images)
    header = struct.pack("<HHH", 0, 1, len(images))
    entries = b""
    for size, data in zip(sizes, images, strict=True):
        entries += struct.pack("<BBBBHHII", size % 256, size % 256, 0, 0, 1, 32, len(data), offset)
        offset += len(data)
    return header + entries + b"".join(images)


def svg():
    """The mark as SVG (used by browsers that support SVG favicons)."""
    hex_colour = "#{:02X}{:02X}{:02X}".format
    rects = "".join(
        f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="{hex_colour(*c)}"/>'
        for x, y, w, h, c in SHAPES
    )
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {GRID} {GRID}">'
        f'<rect width="{GRID}" height="{GRID}" fill="{hex_colour(*INK)}"/>{rects}</svg>\n'
    )


def manifest():
    return {
        "name": "Runnify",
        "short_name": "Runnify",
        "description": "Find the songs that make you run faster.",
        "start_url": "/dashboard",
        "display": "standalone",
        "background_color": "#FFFFFF",
        "theme_color": "#111111",
        "icons": [
            {
                "src": "/static/img/icon-192.png",
                "sizes": "192x192",
                "type": "image/png",
                "purpose": "any maskable",
            },
            {
                "src": "/static/img/icon-512.png",
                "sizes": "512x512",
                "type": "image/png",
                "purpose": "any maskable",
            },
        ],
    }


def main():
    img = OUT / "img"
    img.mkdir(parents=True, exist_ok=True)
    (img / "favicon.svg").write_text(svg(), encoding="utf-8", newline="\n")
    (img / "favicon.ico").write_bytes(ico([16, 32, 48]))
    (img / "apple-touch-icon.png").write_bytes(png(180))
    (img / "icon-192.png").write_bytes(png(192))
    (img / "icon-512.png").write_bytes(png(512))
    (OUT / "site.webmanifest").write_text(
        json.dumps(manifest(), indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    print(f"Wrote the favicon set to {img}")


if __name__ == "__main__":
    main()
